### ISSUE TITLE
error when attempting to call run.sh with literal '-c'

### ISSUE THREAD

**Issue by kevinushey** [NicolaasWeideman/RegexStaticAnalysis#1]
I bumped into this while attempting to run the analyzer with a regular expression which itself attempts to look for a `-c` (plus other stuff):

```
./run.sh -c '-c hello'
```

gives

```
$ ./run.sh -c '-c hello'
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at driver.Main.setupRegexesReader(Main.java:285)
        at driver.Main.main(Main.java:109)
```

A very minor issue, but thought it was worth reporting -- thanks for putting together and sharing such a handy tool!

**Comment by NicolaasWeideman** [comment]
Thanks, I changed the syntax to enter regexes from the command line in the following format:
./run.sh --regex="-c hello"
I would recommend, however, to pass regexes rather via an input file:
./run.sh --if=file.txt

**Comment by kevinushey** [comment]
Awesome; thanks! I'll give it a shot.
